### ISSUE TITLE
Remove submodules

### ISSUE THREAD

**Issue by someshsingh22** [midas-research/calling-out-bluff#3]
@meharbhatia Can you remove the .git files and push from submodules created in commit https://github.com/midas-research/calling-out-bluff/commit/b003647d9500b39cb89c4331041a1d4f44a85d82, specifically :
- Model4(BERT)
- Model5(MemoryNets)

or add links to the repositories these are being maintained in, right now they appear as empty folders if you clone them.

**Comment by meharbhatia** [comment]
Resolved. Closing issue.
